/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Rect {
  x: number
  y: number
  width: number
  height: number
}
export interface Resolution {
  width: number
  height: number
}
export interface Screen {
  /** The dimensions and location of the screen. */
  frame: Rect
  /** The current location and dimensions of the visible screen. */
  visibleFrame: Rect
  /** Native resolution. */
  resolution: Resolution
  /** Whether the screen is the primary screen. */
  primary: boolean
}
export declare function screens(): Array<Screen>
